---@class TMJRoot
---@field height integer
---@field width integer
---@field tileheight integer
---@field tilewidth integer
---@field tilesets TSJTilesetRef[]|TSJTileset[]
---@field layers TMJLayer[]
---@field properties TProperty[] | table<string,TProperty>
